routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('phone', 'PhoneServiceController');
Route::resource('internet', 'InternetServiceController');
Route::resource('cable', 'CableServiceController');
Route::resource('channel', 'ChannelController');
Route::resource('package', 'PackageController');

Route::post('package/add','AdminController@addPackage')->name('package.add');
Route::get('users', 'AdminController@indexUsers')->name('user.index');
Route::get('user/{user}', 'AdminController@showUser')->name('user.show');
Route::post('user/approved', 'AdminController@approvePackage')->name('user.ok');

Route::get('invoices', 'InvoiceController@index')->name('invoice.index');
Route::get('invoice/{invoice}', 'InvoiceController@show')->name('invoice.show');

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/home.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Admin Panel - Bienvenido</div>
                <div class="card-body">
                    <div class="row mt-3">
                        <div class="col-6">
                            <h3>Servicios</h3>
                            <div>
                                <ul class="list-group list-group-flush">
                                <li class="list-group-item"><a class="btn" href="{{ route('phone.index') }} ">Teléfono</a></li>
                                <li class="list-group-item"><a class="btn" href="{{ route('internet.index') }} ">Internet</a></li>
                                <li class="list-group-item"><a class="btn" href="{{ route('channel.index') }} ">Canales</a></li>
                                <li class="list-group-item"><a class="btn" href="{{ route('cable.index') }} ">Cable</a></li>
                                <li class="list-group-item"><a class="btn" href="{{ route('package.index') }} ">Paquetes</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-6">
                            <h3>Creación de Servicios</h3>
                            <div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><a class="btn" href="{{ route('phone.create') }} ">Teléfono</a></li>
                                    <li class="list-group-item"><a class="btn" href="{{ route('internet.create') }} ">Internet</a></li>
                                    <li class="list-group-item"><a class="btn" href="{{ route('channel.create') }} ">Canal</a></li>
                                    <li class="list-group-item"><a class="btn" href="{{ route('cable.create') }} ">Cable</a></li>
                                    <li class="list-group-item"><a class="btn" href="{{ route('package.create') }} ">Paquete</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                   <div class="col-12">
                        <h3>Usuarios</h3>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item" ><a class="btn" href="{{ route('user.index') }} ">Usuarios</a></li>
                        </ul>
                    </div>
                    <div class="col-12">
                        <h3>Programación</h3>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item" ><a class="btn" href="">Programación</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/showUser.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="float-left">
                        <h3>{{$user->name}}</h3>
                    </div>
                </div>
                <div class="card-body">
                    @forelse ($user->invoices as $invoice)
                    @if ($loop->first)
                    <div class="col-md-12 text-center">
                        @if ( auth()->user() == $user ) <h1>Tus facturas </h1> @else <h1>Las facturas de este usuario </h1> @endif
                    </div>
                    @endif
                    
                    <div class="col-md-12 mt-2">
                        <div class="card">
                            <div class="card-header"> <a class="btn" href="{{ route('invoice.show', $invoice) }}"> Factura numero  #{{$invoice->id}}</a> del mes:<strong>{{ $invoice->updated_at->format(' m/Y') }} </strong> </div>
                        </div>
                    </div>
                    @empty
                    <div class="col-md-8 text-center">
                        <h1>Este usuario aun no tienes facturas disponibles!</h1>
                    </div>
                    @endforelse
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse ($users as $user)
        @if ($loop->first)
        <div class="col-md-8 text-center">
            <h1>Usuarios Registrados</h1>
        </div>
        @endif
        
        <div>
            <div class="card">
                <div class="card-header">
                    <a class="btn float-left" href="{{ route('user.show', $user) }}"> {{$user->name}} </a>
                    @if( $user->hasPackage() && !$user->isPackageApproved() )
                    <form action="{{ route('user.ok') }}" method="POST">
                    @csrf
                    <input type="hidden" name="user_id" value="{{$user->id}}">
                    <button type="submit" class="float-right btn btn-outline-primary">Aprobar</button>
                    </form>
                    @endif
                </div>
                <div class="card-body">
                    @if ( $user->hasPackage() )
                        Suscrito a <a href="{{route('package.show', $user->package)}}">{{$user->package->title}}</a>
                        <div class="float-right">
                            @if ( $user->isPackageApproved() )
                                <span class="text-success">Aprobado.</span>
                            @else
                                <span class="text-danger">Esta subscripcion aun no ha sido aprobada.</span>
                            @endif
                        </div>
                    @else
                        <h3 class="text-center">Este usuario no esta suscrito a ningun paquete!</h3>
                    @endif
                <div>
                </div>
            </div>
        </div>
        @empty
        <div class="col-md-8 text-center">
            <h1>No hay usuarios registrados!</h1>
        </div>
        @endforelse
    </div>
</div>
@endsection