routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('phone', 'PhoneServiceController');
Route::resource('internet', 'InternetServiceController');
Route::resource('cable', 'CableServiceController');
Route::resource('channel', 'ChannelController');
Route::resource('package', 'PackageController');

Route::post('package/add','AdminController@addPackage')->name('package.add');
Route::get('users', 'AdminController@indexUsers')->name('user.index');
Route::get('user/{user}', 'AdminController@showUser')->name('user.show');
Route::post('user/approved', 'AdminController@approvePackage')->name('user.ok');

Route::get('invoices', 'InvoiceController@index')->name('invoice.index');
Route::get('invoice/{invoice}', 'InvoiceController@show')->name('invoice.show');

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/services/phone/create.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Registrar nuevo servicio</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('phone.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Descripcion</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" required>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">Precio (BsS) </label>

                            <div class="col-md-6">
                                <input id="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price" value="{{ old('price') }}" required>

                                @if ($errors->has('price'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="minutes" class="col-md-4 col-form-label text-md-right">Minutos</label>

                            <div class="col-md-6">
                                <input id="minutes" type="number" class="form-control{{ $errors->has('minutes') ? ' is-invalid' : '' }}" name="minutes" value="{{ old('minutes') }}" required>

                                @if ($errors->has('minutes'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('minutes') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/services/phone/edit.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">Editar servicio {{ $phone->title}}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('phone.update', $phone) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ $phone->title }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Descripcion</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ $phone->description }}" required>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">Precio (BsS) </label>

                            <div class="col-md-6">
                                <input id="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price" value="{{ $phone->price }}" required>

                                @if ($errors->has('price'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="minutes" class="col-md-4 col-form-label text-md-right">Minutos</label>

                            <div class="col-md-6">
                                <input id="minutes" type="number" class="form-control{{ $errors->has('minutes') ? ' is-invalid' : '' }}" name="minutes" value="{{ $phone->minutes }}" required>

                                @if ($errors->has('minutes'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('minutes') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Editar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/services/phone/index.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse ($phones as $phone)
        @if ($loop->first)
        <div class="col-md-8 text-center">
            <h1>Paquete De Teléfono Disponibles</h1>
        </div>
        @endif
        
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-header"> <a class="btn" href="{{ route('phone.show', $phone) }}"> {{$phone->title}} </a></div>
                <div class="card-body">
                <div>
                    <p>Descripción: {{$phone->description}}</p>
                    <p>Minutos: {{$phone->minutes}} min</p>
                    <p>Precio: {{$phone->price}} Bs.</p>
                </div>
                </div>
            </div>
        </div>
        @empty
        <div class="col-md-8 text-center">
            <h1>Aun no hay paquetes disponibles!</h1>
        </div>
        @endforelse
    </div>
</div>
@endsection

resources/views/services/phone/show.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h1>Paquete De Teléfono Disponible</h1>
        </div>
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-header"> <a class="btn" href="{{ route('phone.show', $phone) }}"> {{$phone->title}} </a></div>
                <div class="card-body">
                <div>
                    <p>Descripción: {{$phone->description}}</p>
                    <p>Minutos: {{$phone->minutes}} min</p>
                    <p>Precio: {{$phone->price}} Bs</p>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection