routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('phone', 'PhoneServiceController');
Route::resource('internet', 'InternetServiceController');
Route::resource('cable', 'CableServiceController');
Route::resource('channel', 'ChannelController');
Route::resource('package', 'PackageController');

Route::post('package/add','AdminController@addPackage')->name('package.add');
Route::get('users', 'AdminController@indexUsers')->name('user.index');
Route::get('user/{user}', 'AdminController@showUser')->name('user.show');
Route::post('user/approved', 'AdminController@approvePackage')->name('user.ok');

Route::get('invoices', 'InvoiceController@index')->name('invoice.index');
Route::get('invoice/{invoice}', 'InvoiceController@show')->name('invoice.show');

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Package.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\CableService as Cable;
use App\InternetService as Internet;
use App\PhoneService as Phone;
use App\User;

class Package extends Model
{
    /**
     * @var array
     */
    protected $guarded = [];

    public function cable(){
        return $this->belongsTo(Cable::class, 'cable_service_id');
    }

    public function internet(){
        return $this->belongsTo(Internet::class, 'internet_service_id');
    }

    public function phone(){
        return $this->belongsTo(Phone::class, 'phone_service_id');
    }

    public function user(){
        return $this->hasMany(User::class);
    }

    public function getTotalPrice(){
        $total = 0;
        if( $this->hasCable() ) $total+= $this->cable->price;
        if( $this->hasInternet() ) $total+= $this->internet->price;
        if( $this->hasPhone() ) $total+= $this->phone->price;
        return $total;
    }
    public function hasCable() : bool {return !is_null($this->cable); }

    public function hasInternet() : bool {return !is_null($this->internet); }
    
    public function hasPhone() : bool {return !is_null($this->phone); }
}

app/Http/Controllers/PackageController.php
<?php

namespace App\Http\Controllers;

use App\Package;
use Illuminate\Http\Request;

use App\CableService as Cable;
use App\InternetService as Internet;
use App\PhoneService as Phone;

class PackageController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin')->except(['show', 'index']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $packages = Package::all();
        return view('services.package.index', compact('packages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cables = Cable::with('channels')->get();
        $internets = Internet::all();
        $phones = Phone::all();

        return view('services.package.create' , compact('phones' , 'cables' , 'internets'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|min:10|max:50',
            'description' => 'required|string|min:10|max:150',
            'phone' => 'nullable',
            'cable' => 'nullable',
            'internet' => 'nullable',
        ]);
        if( $validated['phone'] == 0 and $validated['cable']  == 0 and $validated['internet'] == 0) return redirect()->back()->withErrors('El paquete tiene que tener al menos un servicio!');

        $package = Package::create( array_only($validated, ['title', 'description'] ) );

        if( array_has($validated , 'internet' ) and $validated['internet'] != 0  ){
            $internet = Internet::find( $validated['internet'] );
            if( is_null( $internet ) ) return redirect()->back()->withErrors('El servicio de internet seleccionado no existe, por favor intentelo de nuevo');
            $package->internet()->associate( $internet );
        }

        if( array_has($validated , 'cable' ) and $validated['cable'] != 0  ){
            $cable = Cable::find( $validated['cable'] );
            if( is_null( $cable ) ) return redirect()->back()->withErrors('El servicio de cable seleccionado no existe, por favor intentelo de nuevo');
            $package->cable()->associate( $cable );
        }

        if( array_has($validated , 'phone' ) and $validated['phone'] != 0  ){
            $phone = Phone::find( $validated['phone'] );
            if( is_null( $phone ) ) return redirect()->back()->withErrors('El servicio de telefonia seleccionado no existe, por favor intentelo de nuevo');
            $package->phone()->associate( $phone );
        }
        $package->save();
        return redirect()->route('package.show' , $package)->withSuccess('Paquete creado con exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function show(Package $package)
    {
        $package->loadMissing(['cable', 'internet', 'phone', 'user']);
        return view('services.package.show', compact('package'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function edit(Package $package)
    {
        $cables = Cable::with('channels')->get();
        $internets = Internet::all();
        $phones = Phone::all();

        return view('services.package.edit' , compact('phones' , 'cables' , 'internets', 'package'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Package $package)
    {
        $validated = $request->validate([
            'title' => 'required|string|min:10|max:50',
            'description' => 'required|string|min:10|max:150',
            'phone' => 'nullable',
            'cable' => 'nullable',
            'internet' => 'nullable',
        ]);
        if( $validated['phone'] == 0 and $validated['cable']  == 0 and $validated['internet'] == 0) return redirect()->back()->withErrors('El paquete tiene que tener al menos un servicio!');
        if( array_has($validated , 'internet' ) and $validated['internet'] != 0  ){
            $internet = Internet::find( $validated['internet'] );
            if( is_null( $internet ) ) return redirect()->back()->withErrors('El servicio de internet seleccionado no existe, por favor intentelo de nuevo');
            $package->internet()->associate( $internet );
        }

        if( array_has($validated , 'cable' ) and $validated['cable'] != 0  ){
            $cable = Cable::find( $validated['cable'] );
            if( is_null( $cable ) ) return redirect()->back()->withErrors('El servicio de cable seleccionado no existe, por favor intentelo de nuevo');
            $package->cable()->associate( $cable );
        }

        if( array_has($validated , 'phone' ) and $validated['phone'] != 0  ){
            $phone = Phone::find( $validated['phone'] );
            if( is_null( $phone ) ) return redirect()->back()->withErrors('El servicio de telefonia seleccionado no existe, por favor intentelo de nuevo');
            $package->phone()->associate( $phone );
        }

        $package->fill( array_only($validated, ['title', 'description'] ) );

        $package->save();
        return redirect()->route('package.show' , $package)->withSuccess('Paquete creado con exito!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function destroy(Package $package)
    {
        //
    }
}

resources/views/services/package/create.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Crea un nuevo paquete de Servicios</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('package.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Descripcion</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" required>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <label for="cable" class="col-md-4 col-form-label text-md-right">Servicios de cable </label>
                            <div class="col-md-6">
                        @forelse ($cables as $cable)
                            @if ($loop->first)
                            <select id="cable" class="form-control{{ $errors->has('cable') ? ' is-invalid' : '' }}" name="cable" >
                            <option value="0" >Seleccione un servicio de cable</option>
                            @endif
                            <option value="{{$cable->id}}" {{ old('cable') == $cable->id ? ' selected ' : '' }} 
                                    data-title="{{$cable->title}}" data-price="{{$cable->price}}" data-description="{{$cable->description}}" 
                                    data-channels="{{$cable->channels}}" >
                                    {{$cable->title}} </option>
                            @if ($loop->last)
                            </select>                       
                            @endif
                            
                        @empty
                            <h6>No hay servicios de cable disponible! Puedes crear uno <a href="{{route('cable.create')}}">aqui</a>.</h6>
                        @endforelse
                            </div>
                            <div id="cable-wrapper" class="col-md-6 mx-auto my-2 p-3 cable" style="display:none">
                                <div  >
                                    <div class="float-left">
                                        <h5 id="cable-title" class="font-weight-bold"> </h5>
                                        <h6 id="cable-channels" class=""></h6>
                                        <p id="cable-description"></p>
                                    </div>
                                    <div class="float-right">
                                        <h5 class=" text-success"> Seleccionado </h5>
                                        <span id="cable-price" class=""></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Servicios de telefonia </label>
                            <div class="col-md-6">
                        @forelse ($phones as $phone)
                            @if ($loop->first)
                            <select id="phone" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" >
                            <option value="0" >Seleccione un servicio de telefonia</option>
                            @endif
                            <option value="{{$phone->id}}" {{ old('phone') == $phone->id ? ' selected ' : '' }} 
                                    data-title="{{$phone->title}}" data-price="{{$phone->price}}" data-description="{{$phone->description}}" data-minutes="{{$phone->minutes}}">
                                    {{$phone->title}} - {{ $phone->minutes}} Minutos </option>
                            @if ($loop->last)
                            </select>                       
                            @endif
                            
                        @empty
                            <h6>No hay servicios de telefonia disponible! Puedes crear uno <a href="{{route('phone.create')}}">aqui</a>.</h6>
                        @endforelse
                            </div>
                            <div id="phone-wrapper" class="col-md-6 mx-auto my-2 p-3 phone" style="display: none;">
                                <div >
                                    <div class="float-left">
                                        <h5 id="phone-title" class="font-weight-bold"> </h5>
                                        <h6 id="phone-minutes" class=""></h6>
                                        <p id="phone-description"></p>
                                    </div>
                                    <div class="float-right">
                                        <h5 class=" text-success"> Seleccionado </h5>
                                        <span id="phone-price" class=""></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="internet" class="col-md-4 col-form-label text-md-right">Servicios de Internet </label>
                            <div class="col-md-6">
                        @forelse ($internets as $internet)
                            @if ($loop->first)
                            <select id="internet" class="form-control{{ $errors->has('internet') ? ' is-invalid' : '' }}" name="internet" >
                            <option value="0" >Seleccione un servicio de Internet</option>
                            @endif
                            <option value="{{$internet->id}}" {{ old('internet') == $internet->id ? ' selected ' : '' }} 
                                    data-title="{{$internet->title}}" data-price="{{$internet->price}}" data-description="{{$internet->description}}" data-speed="{{$internet->speed}}">
                                    {{$internet->title}} - {{ $internet->speed}} Mbs </option>
                            @if ($loop->last)
                            </select>                       
                            @endif
                            
                        @empty
                            <h6>No hay servicios de Internet disponible! Puedes crear uno <a href="{{route('internet.create')}}">aqui</a>.</h6>
                        @endforelse
                            </div>
                            <div id="internet-wrapper" class="col-md-6 mx-auto my-2 p-3 internet" style="display: none;">
                                <div >
                                    <div class="float-left">
                                        <h5 id="internet-title" class="font-weight-bold"> </h5>
                                        <h6 id="internet-speed" class=""></h6>
                                        <p id="internet-description"></p>
                                    </div>
                                    <div class="float-right">
                                        <h5 class=" text-success"> Seleccionado </h5>
                                        <span id="internet-price" class=""></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('readyFunction')
//Function to display the cable features when a new cable service is selected
function changeCable(){
    $('#cable-title').text( $('#cable').find('option:selected').data('title') )
    $('#cable-price').text( $('#cable').find('option:selected').data('price') + ' (BsS) ' )
    var channels = $('#cable').find('option:selected').data('channels');
    var texto = '';
    for(var ch of channels){
        texto += ' -' + ch.title + " <br> "
    }
    console.log(texto)
    $('#cable-channels').html( texto )
    $('#cable-description').text( $('#cable').find('option:selected').data('description') )
    $('#cable-wrapper').show()
}
// Check when the page is loaded
if ($('#cable').val() !=0 && $('#cable').val() != undefined  ){
    changeCable()
}
//Change when the new cable service is selected
$('#cable').change(function(){
    if( this.value == 0){
        $('#cable-wrapper').hide()
    } else {
        changeCable()
    }
});

function changePhone(){
    $('#phone-title').text( $('#phone').find('option:selected').data('title') )
    $('#phone-price').text( $('#phone').find('option:selected').data('price') + ' (BsS) ' )
    $('#phone-minutes').text( $('#phone').find('option:selected').data('minutes') + ' Minutos ' )
    $('#phone-description').text( $('#phone').find('option:selected').data('description') )
    $('#phone-wrapper').show()
}

if ($('#phone').val() !=0 && $('#phone').val() != undefined ){
    changePhone()
}

$('#phone').change(function(){
    if( this.value == 0){
        $('#phone-wrapper').hide()
    } else {
        changePhone()
    }
});

function changeInternet(){
    $('#internet-title').text( $('#internet').find('option:selected').data('title') )
    $('#internet-price').text( $('#internet').find('option:selected').data('price') + ' (BsS) ' )
    $('#internet-speed').text( $('#internet').find('option:selected').data('speed') + ' Mbs ' )
    $('#internet-description').text( $('#internet').find('option:selected').data('description') )
    $('#internet-wrapper').show()
}

if ($('#internet').val() !=0 && $('#internet').val() != undefined ){
    changeInternet()
}

$('#internet').change(function(){
    if( this.value == 0){
        $('#internet-wrapper').hide()
    } else {
        changeInternet()
    }
});
@endsection

resources/views/services/package/index.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse ($packages as $package)
        @if ($loop->first)
        <div class="col-md-8 text-center">
            <h1>Paquetes Disponibles</h1>
        </div>
        @endif
        
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-header"> <a class="btn" href="{{ route('package.show', $package) }}"> {{$package->title}} </a></div>
                <div class="card-body">
                <div>
                    <h5>Descripcion:</h5>
                    <p>
                        {{$package->description}}
                    </p>
                </div>
                Incluye: 
                <ul>
                    @if ( $package->hasCable() )
                    <li>
                        <a href="{{ route('cable.show', $package->cable) }}" class="btn"> {{$package->cable->title}} </a>
                    </li>    
                    @endif
                    @if ( $package->hasPhone() )
                    <li>
                        <a href="{{ route('phone.show', $package->phone) }}" class="btn"> {{$package->phone->title}} </a>
                    </li>    
                    @endif
                    @if ( $package->hasInternet() )
                    <li>
                        <a href="{{ route('internet.show', $package->internet) }}" class="btn"> {{$package->internet->title}} </a>
                    </li>    
                    @endif
                </ul>
                </div>
            </div>
        </div>
        @empty
        <div class="col-md-8 text-center">
            <h1>Aun no hay paquetes disponibles!</h1>
        </div>
        @endforelse
    </div>
</div>
@endsection

resources/views/services/package/show.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="float-left">
                        <h3>{{$package->title}}</h3>
                    </div>
                    @if ( auth()->user()->isAdmin())                        
                    <div class=" d-inline-flex float-right ">
                        <a href="{{route('package.edit', $package)}}" class="btn btn-outline-success btn-md mr-2">Editar</a>
                        <form action="{{route('package.destroy', $package)}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" href="{{route('package.edit', $package)}}" class="btn btn-danger btn-md">Borrar</button>
                        </form>
                    </div>
                    @endif
                </div>
                <div class="card-body">
                    <h5 class="float-right">
                        Precio total del paquete: <strong>{{ $package->getTotalPrice() }}</strong> (BsS)
                    </h5>
                    <h4>Descripcion: </h4>
                    <p>
                        {{$package->description}}
                    </p>
                    <hr>
                    <h4>Incluye:</h4>
                    @if ( $package->hasCable() )
                    <hr>
                        <h5 class="float-right">
                            Precio total del servicio: <strong>{{ $package->cable->price }}</strong> (BsS)
                        </h5>
                        <h5>
                            Nombre del servicio <a href="{{route('cable.show', $package->cable)}}" class="btn text-primary"><strong> {{$package->cable->title}} </strong> </a>
                        </h5>
                        <p>
                            {{$package->cable->description}}
                        </p>
                        @forelse ($package->cable->channels as $channel)
                            @if ($loop->first)
                                <ul>                                    
                            @endif
                            <li>
                                <h6><a href="{{route('channel.show', $channel)}}" class="btn">{{$package->title}}</a></h6>
                                <p>
                                    {{$channel->description}}    
                                </p> 
                            </li>
                            @if ($loop->last)
                                </ul>
                            @endif                         
                        @empty
                            <h6 class="text-danger">Este servicio de cable no tiene canales disponibles!</h6>
                        @endforelse
                    @endif
                    @if ( $package->hasInternet() )
                    <hr>
                        <h5 class="float-right">
                            Precio total del servicio: <strong>{{ $package->internet->price }}</strong> (BsS)
                        </h5>
                        <h5>
                            Nombre del servicio <a href="{{route('internet.show', $package->internet)}}" class="btn text-primary"><strong> {{$package->internet->title}} </strong> </a>
                        </h5>
                        <p>
                            {{$package->internet->description}}
                        </p>
                        <h5 class="">{{$package->internet->speed}} (Mbs) !</h5>
                    @endif
                    @if ( $package->hasPhone() )
                    <hr>
                        <h5 class="float-right">
                            Precio total del servicio: <strong>{{ $package->phone->price }}</strong> (BsS)
                        </h5>
                        <h5>
                            Nombre del servicio <a href="{{route('phone.show', $package->phone)}}" class="btn text-primary"><strong> {{$package->phone->title}} </strong> </a>
                        </h5>
                        <p>
                            {{$package->phone->description}}
                        </p>
                        <h5 class="">{{$package->phone->minutes}} Minutos! </h5>
                    @endif
                    <hr>
                    @unless( auth()->user()->isAdmin() )
                    <div class="text-center">
                        <form action="{{route('package.add')}}" method="POST">
                        @csrf
                        <input type="hidden" name="package_id" value="{{$package->id}}">
                        <button class="text-center btn btn-large btn-primary">Suscribirme a este paquete!</button>
                        </form>
                    </div>
                    @endunless
                </div>
            </div>
        </div>
    </div>
</div>
@endsection